server:
  host: doacao.org
  port: 8080

api:
  info:
    title: Doação de livros
    description: API projeto doação de livros
    version: 1.0
    contact:
      name: Kevin Cavenatti Bueno
      url: http://github.com/apidoacao
      email: kevin_cavenatti@hotmail.com

spring:
  application:
    name: apidoacao
  jpa:
    generate-ddl: false
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: example
    data: classpath:db/migrations/data/V1__data_apidoacao.sql
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    locations: classpath:db/migrations/schema
    data: classpath:db/migrations/schema
  kafka:
    topics:
      topic-analise-transacao: analise-transacao
      topic-aprovacao-transacao: aprovacao-transacao
    bootstrap-servers: localhost:9092
    group-id: apiDoacao
  feign:
    clients:
      cep:
        name: viacep
        base-uri: viacep.com.br


security:
  jwt:
    expiracao: 60
    chave-assinatura: OTMwZTM0M2QtOTNkZC00OWVhLWFmNTMtOWVlMmJiOWFkZjA0